// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadPrompts() {
  return window['go']['main']['App']['LoadPrompts']();
}

export function ProcessIdeaForm(arg1) {
  return window['go']['main']['App']['ProcessIdeaForm'](arg1);
}

export function ProcessUserInput(arg1) {
  return window['go']['main']['App']['ProcessUserInput'](arg1);
}
