// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadPrompts():Promise<Array<main.Message>>;

export function ProcessIdeaForm(arg1:main.RawFormData):Promise<void>;

export function ProcessUserInput(arg1:string):Promise<string>;
